# Browsersync port
PORT: 8080

# Purgecss settings
PURGECSS:
  whitelist:
  - w-100
  - vw-100
  whitelistPatterns:
    - !!js/regexp /order/gm
    - !!js/regexp /text/gm
  whitelistPatternsChildren:

# Gulp path references
PATHS:
  # Path to "dist" folder
  dist: dist
  # Paths to Sass libraries, which can then be loaded with @import
  # without the need for the full path "node_modules/.." everytime
  sassLibs:
    - node_modules/foundation-sites/scss
    - node_modules/motion-ui/src
    - node_modules/bootstrap/scss
    - node_modules/uikit/src/scss
  # Path to static assets & ignore some folders
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}/**"
  images:
    - "src/assets/**/*.{jpg,jpeg,png,gif,svg,webp}"
    - "!src/assets/fonts/**"
  # Path to static files to copy to "dist"
  staticFiles:
    - "src/robots.txt"
    - "src/favicon.ico"
    - "src/.htaccess"
    #- "src/site.webmanifest"
  # Additional JS files to copy to "dist/assets/js"
  additionalJsFiles2Copy:
    - "src/assets/js/js-copy/**/*.js"
    #- "node_modules/bootstrap/dist/js/*.js"
  # Additional CSS files to copy to "dist/assets/css"
  additionalCssFiles2Copy:
    - "src/assets/scss/css-copy/**/*.css"
    #- "node_modules/bootstrap/dist/css/*.css"
